version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:1.25.4-alpine3.18
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: /bin/sh -c "nginx -g 'daemon off;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge