version: '3.2'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT-8080}:8080"
    depends_on:
      - mongodb
    networks:
      - backend-network
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: 
      sh -c "npm install && npm run dev"
    volumes:
      - ./:/app
    
  mongodb:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "${MONGODB_PORT-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    networks:
      - backend-network
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.18
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    ports:
      - "8888:8081"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
