FROM node:20.11.1-alpine3.19

# Create app directory

WORKDIR /app

# Install app dependencies

COPY package*.json ./

RUN npm ci

# Bundle app source

COPY . .

EXPOSE $PORT

CMD ["npm", "run", "dev"]